run:
  timeout: 5m
  skip-dirs:
    - apps
    - packages
    - docs

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck

linters-settings:
  govet:
    check-shadowing: true
  revive:
    confidence: 0.8

issues:
  exclude-use-default: false
